version: '3.8'

services:
  weaviate:
    image: ec1e4093047a
    platform: linux/amd64
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    env_file:
      - .env
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      ENABLE_MODULES: ''
      DEFAULT_VECTORIZER_MODULE: ''
      CLUSTER_HOSTNAME: 'node1'
    restart: unless-stopped
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
