version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.30.2
    platform: linux/amd64
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    env_file:
      - .env
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      ENABLE_MODULES: ''
      DEFAULT_VECTORIZER_MODULE: ''
      CLUSTER_HOSTNAME: 'node1'
    restart: unless-stopped
    networks:
      - rag_network

  fastapi:
    build: ./app
    container_name: resume-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - WEAVIATE_COLLECTION=Candidates
    restart: unless-stopped
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
