version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.1
    container_name: weaviate
    platform: linux/arm64
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      ENABLE_MODULES: 'text2vec-openai'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      CLUSTER_HOSTNAME: 'node1'
    restart: unless-stopped
