version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.30.2
    container_name: weaviate
    platform: linux/arm64
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    env_file:
      - .env
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      ENABLE_MODULES: ''  # ❌ 禁用所有模块（手动向量化）
      DEFAULT_VECTORIZER_MODULE: ''  # ❌ 不使用默认向量器
      CLUSTER_HOSTNAME: 'node1'
    restart: unless-stopped
    networks:
      - rag_network

  n8n-custom:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    container_name: n8n-custom
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
      - ./data/resumes:/home/node/data/resumes
      - ./requirements.txt:/data/requirements.txt
      - ./scripts:/data/scripts
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - rag_network

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    ports:
      - "8081:8080"
    volumes:
      - ./nocodb_data:/usr/app/data
    restart: unless-stopped
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge

volumes:
  weaviate_data:
  n8n_data: